name: Build and push image to GCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Checking path
        run: |
          ls
          pwd 
          cd "${{ github.workspace }}/Skipify/src/deidentify"

      - name: Build Docker image
        id: build-image
        run: |
          cd "${{ github.workspace }}/Skipify/src/deidentify"
          docker build -t first-gowtham .
          echo "IMAGE_URL=gcr.io/stovlsandboxnew-399705/firstgowtham:${{ github.sha }}" >> $GITHUB_ENV

      - name: Authenticate with GCR
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.CLOUDRUN_GCP }}'

      - name: Push Docker image to GCR
        run: |
          docker tag first-gowtham gcr.io/stovlsandboxnew-399705/firstgowtham:${{ github.sha }}
          gcloud auth configure-docker
          docker push gcr.io/stovlsandboxnew-399705/firstgowtham:${{ github.sha }}
