name: Build and push image to GCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Building Docker image
      run: |
        cd /home/runner/work/github-actions/github-actions/Skipify/src/deidentify
        docker build -t cloudrun_image .

    - name: Determine image tag
      id: tag
      run: echo ::set-output name=TAG::v${{ github.run_number }}

    # Authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.CLOUDRUN_GCP }}'

    - name: Push image to GCR
      run: |-
        docker tag cloudrun_image gcr.io/stovlsandboxnew-399705/cloudrun_image:${{ steps.tag.outputs.TAG }}
        gcloud auth configure-docker
        docker push gcr.io/stovlsandboxnew-399705/cloudrun_image:${{ steps.tag.outputs.TAG }}
    
