name: Deploy Cloud Run with Terraform

on:
  workflow_run:
    workflows: ["Build and push image to GCR"]
    types:
      - completed

jobs:
  deploy_cloud_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Contents of Source Directory
        run: |
          ls -R "${{ github.workspace }}/Skipify/src/deidentify"

      - name: List Contents of Downloaded Directory
        run: |
          ls -R "${{ github.workspace }}/downloaded-artifacts"

      - name: Download Docker Image URL
        uses: actions/download-artifact@v2
        with:
          name: docker-image-url
          path: "${{ github.workspace }}/downloaded-artifacts"

      - name: Get Docker Image URL
        id: get-image-url
        run: |
          echo "IMAGE_URL=$(cat downloaded-artifacts/IMAGE_URL)"
          echo "Retrieved Image URL: $IMAGE_URL"  # Print to workflow log

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: |
          pwd
          cd "${{ github.workspace }}/Skipify/tf/cloudrun/deidentify"
          ls
          terraform init

      - name: Terraform Plan
        run: |
          cd "${{ github.workspace }}/Skipify/tf/cloudrun/deidentify"
          ls
          terraform plan

      - name: Terraform Apply
        run: |
          cd "${{ github.workspace }}/Skipify/tf/cloudrun/deidentify"
          # Use the IMAGE_URL variable retrieved from the artifact
          terraform apply -auto-approve -var="image_url=${{ steps.get-image-url.outputs.IMAGE_URL }}"
