name: Build and push image to GCR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Checking path
      run: |
        ls
        pwd 
        cd /home/runner/work/test-actions/test-actions/Skipify/tf/cloudrun


    # Authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.CLOUDRUN_TEST }}'

    - name: Checking path
      run: |
        ls
        pwd 
        cd /home/runner/work/test-actions/test-actions/Skipify/tf/cloudrun
        ls

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: |
        pwd
        cd /home/runner/work/test-actions/test-actions/Skipify/tf/cloudrun
        ls
        terraform init

    - name: Terraform Plan
      run: |
        cd /home/runner/work/test-actions/test-actions/Skipify/tf/cloudrun
        ls
        terraform plan

    - name: Terraform Apply
      run: |
        cd /home/runner/work/test-actions/test-actions/Skipify/tf/cloudrun
        terraform apply -auto-approve
