name: Deploy Cloud Run with Terraform

on:
  workflow_run:
    workflows: ["Build and push image to GCR"]
    types:
      - completed

jobs:
  deploy_cloud_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Download Docker image URL artifact from the first pipeline
      - name: Download Docker Image URL
        uses: actions/download-artifact@v2
        with:
          name: docker-image-url
          path: .

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: |
          pwd
          cd /home/runner/work/github-actions/github-actions/Skipify/tf/cloudrun/deidentify
          ls
          terraform init

      - name: Terraform Plan
        run: |
          cd /home/runner/work/github-actions/github-actions/Skipify/tf/cloudrun/deidentify
          ls
          terraform plan

      - name: Terraform Apply
        run: |
          cd /home/runner/work/github-actions/github-actions/Skipify/tf/cloudrun/deidentify
          # Use the IMAGE_URL variable retrieved from the artifact
          terraform apply -auto-approve -var="image_url=$(cat docker-image-url/IMAGE_URL)"
